// src/components/posts/how-i-made-this/SimpleCounter.vue
<script setup lang="ts">
import { ref, onMounted, watchEffect } from 'vue';
import { createDomLogger } from '@/utils/dom';

const count = ref(0);

onMounted(() => {
  const logger = createDomLogger('.component-logs');
  logger.log('Vue SimpleCounter is interactive');
  watchEffect(() => logger.log(`Vue count is ${count.value}`));
});
</script>

<template>
  <div class="my-10 flex items-center gap-5 justify-center">
    <button
      class="btn"
      :disabled="count <= 0"
      @click="--count"
    >-</button>
    <div>
      {{ count }}
    </div>
    <button
      class="btn"
      @click="++count"
    >+</button>
  </div>
</template>

<style scoped lang="scss">
.btn {
  @apply
    dark:bg-red-950
    bg-red-600
    text-white
    flex
    items-center
    disabled:opacity-30
    justify-center
    text-2xl
    h-10
    aspect-square
    rounded-full
    select-none;
}
</style>

// src/components/SimpleCounter.svelte
<script lang="ts">
import { onMount } from 'svelte';
import { createDomLogger, type DomLogger } from '../utils/dom';

let count = 0;
let logger: DomLogger;

onMount(() => {
  logger = createDomLogger('.component-logs');
  logger.log('Svelte SimpleCounter is interactive');
});

$: logger?.log(`Svelte count is ${count}`);
</script>

<div class="my-10 flex items-center gap-5 justify-center">
  <button
    class="btn"
    disabled={count <= 0}
    on:click={() => --count}
  >-</button>
  <div>
    {count}
  </div>
  <button
    class="btn"
    on:click={() => ++count}
  >+</button>
</div>

<style lang="postcss">
.btn {
  @apply
    dark:bg-red-950
    bg-red-600
    text-white
    disabled:opacity-30
    flex
    items-center
    justify-center
    text-2xl
    h-10
    aspect-square
    rounded-full
    select-none;
}
</style>
